name: deploy

on:
  push:
    branches:
      - master
  repository_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: .cache/yarn/v6
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-


      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"        
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ZONE_ID: ${{secrets.CF_ZONE_ID}}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          ROUTE_PREFIX: ${{secrets.CF_ROUTE_PREFIX}}
          TIMESTAMP: ${{ steps.date.outputs.date }}
          